### ISSUE TITLE
AJAX回调函数中重建Page，无法隐藏page组件

### ISSUE THREAD

**Issue by AndyShaw2048** [BBREEZE/xlPaging#2]
问题描述：

我从JQ22下载了大神的代码，在实际使用时，当使用AJAX重新初始化Page组件，
发现 **当页码总数为1 或 小于 0** 时，无法隐藏page组件。

我修改后的代码(大概33行左右)：

```javascript
//如果只有一页并且设置为不显示，则不进行渲染
if((showOne && pageNum === 1) || pageNum == 0){
    $("#page").hide()
    return '';
}
$("#page").show()
```

本人项目中引起问题的代码：
```javascript
                    $.ajax({
                        url: '/detail',
                        type: 'GET',
                        data: {
                        },
                        success: function (data) {
                                $("#page").paging({
                                    nowPage: currentPage, // 当前页码
                                    pageNum: data['count'], // 总页码
                                    buttonNum: 5, //要展示的页码数量
                                    canJump: 1,// 是否能跳转。0=不显示（默认），1=显示
                                    showOne: 0,//只有一页时，是否显示。0=不显示,1=显示（默认）
                                    callback: function (pageNumber) { //回调函数
                                        currentPage = pageNumber;
                                    }
                                });
                            }
```

我在仓库没有发现这一段代码，可能没有及时更新吧，所以希望大神能及时修复

**Comment by BBREEZE** [comment]
谢谢您的回复，我会尽快解决并回复您的。



------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Andy Shaw"<notifications@github.com&gt;; 
发送时间: 2019年11月16日(星期六) 下午4:45
收件人: "BBREEZE/xlPaging"<xlPaging@noreply.github.com&gt;; 
抄送: "Subscribed"<subscribed@noreply.github.com&gt;; 
主题: [BBREEZE/xlPaging] AJAX回调函数中重建Page，无法隐藏page组件 (#2)




问题描述：
 
我从JQ22下载了大神的代码，在实际使用时，当使用AJAX重新初始化Page组件，
 发现 当页码总数为1 或 小于 0 时，无法隐藏page组件。
 
我修改后的代码(大概33行左右)：
 //如果只有一页并且设置为不显示，则不进行渲染 if((showOne &amp;&amp; pageNum === 1) || pageNum == 0){     $("#page").hide()     return ''; } $("#page").show()
 
本人项目中引起问题的代码：
                     $.ajax({                         url: '/detail',                         type: 'GET',                         data: {                         },                         success: function (data) {                                 $("#page").paging({                                     nowPage: currentPage, // 当前页码                                     pageNum: data['count'], // 总页码                                     buttonNum: 5, //要展示的页码数量                                     canJump: 1,// 是否能跳转。0=不显示（默认），1=显示                                     showOne: 0,//只有一页时，是否显示。0=不显示,1=显示（默认）                                     callback: function (pageNumber) { //回调函数                                         currentPage = pageNumber;                                     }                                 });                             }
 
我在仓库没有发现这一段代码，可能没有及时更新吧，所以希望大神能及时修复
 
&mdash;

**Comment by BBREEZE** [comment]
兄弟 我已经更新上来了，谢谢你的意见。我其实都开始有点放弃了。但是你一回复极大地鼓励了我。你要是有什么需求可以直接提。谢谢你 兄弟。

**Comment by AndyShaw2048** [comment]
我得谢谢你的无私开源呢，加油吧！
